coverage:
  precision: 2
  round: down
  range: "70...100"
  ignore:
    - "src/main/java/com.thalesdeluca.salesapi/Dto/"
    - "src/main/java/com.thalesdeluca.salesapi/Entity/"
    - "src/main/java/com.thalesdeluca.salesapi/Error/"
    - "src/main/java/com.thalesdeluca.salesapi/Repository/"
    - "src/main/java/com.thalesdeluca.salesapi/Util/"

codecov:
  notify:
    require_ci_to_pass: yes

  status:
    project: yes
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no